---
jupyter:
  jupytext:
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.2'
      jupytext_version: 1.14.4
  kernelspec:
    display_name: Python 3 (ipykernel)
    language: python
    name: python3
---

```{python}
from CitizenUAV.models import InatClassifier
from CitizenUAV.processes import pixel_conf_mat, optimize_image_resnet
from CitizenUAV.data import GTiffDataset, InatDataModule
import numpy as np
import os
import random
from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
import json
from torchvision.transforms.functional import to_pil_image
```

```{python}
from CitizenUAV.data import InatDataModule
train_classes = InatDataModule('/home/ndettmer/ssd_data/inat_subsets/maize_ternary/').ds.classes


class_map = json.dumps({
    'weeds': 'weed',
    'maize': 'zea mays',
    'soil': 'soil'
})

test_data_dir = '/home/ndettmer/ssd_data/UOS_Data'
```

<!-- #region tags=[] jp-MarkdownHeadingCollapsed=true jp-MarkdownHeadingCollapsed=true tags=[] jp-MarkdownHeadingCollapsed=true jp-MarkdownHeadingCollapsed=true tags=[] -->
## Maize Ternary
<!-- #endregion -->

```{python}
train_data_dir = '/home/ndettmer/ssd_data/inat_subsets/maize_ternary'
base_model_path = '/home/ndettmer/experiments/ma/classification/maize_ternary/lightning_logs/version_0/checkpoints/epoch=49-step=43200.ckpt'
plot_dir = '/home/ndettmer/experiments/ma/classification/maize_ternary/plots'

resnet18_path = base_model_path.replace('version_0', 'version_3')
wide_resnet50_2_path = base_model_path.replace('version_0', 'version_2')
resnest50_path = base_model_path.replace('version_0', 'version_4')

train_classes = InatDataModule(train_data_dir).ds.classes
soil_label = train_classes.index('soil')

sample_size = 25
side_len = int(np.sqrt(sample_size))
```

<!-- #region tags=[] jp-MarkdownHeadingCollapsed=true tags=[] jp-MarkdownHeadingCollapsed=true jp-MarkdownHeadingCollapsed=true tags=[] jp-MarkdownHeadingCollapsed=true -->
### 18.05.22
<!-- #endregion -->

```{python}
pred_dir = '/home/ndettmer/experiments/ma/classification/maize_ternary/predictions/220518_maize_rgb_test_area/'
target_dir = os.path.join(test_data_dir, '1805_maize')
ds_path = os.path.join(test_data_dir, '220518_maize_rgb_test_area.tif')
ds = GTiffDataset(ds_path, shape_dir=target_dir, stride=4, normalize=True)
```

<!-- #region tags=[] -->
#### ResNet50
<!-- #endregion -->

version_0

```{python}
predfile = os.path.join(pred_dir, 'version_0/23-02-17_10-57_probability_map.npy')
prob_mask = np.load(predfile)
prob_mask /= prob_mask.max()
```

```{python}
figure, axs = plt.subplots(1, 3, figsize=(15, 15))
for i in range(3):
    label = train_classes[i]
    #heat_map = sns.heatmap(pd.DataFrame(data=prob_mask[i]), annot=True, cmap='Spectral', fmt='g').get_figure()
    axs[i].imshow(prob_mask[i])
    axs[i].set_title(label)
plt.savefig(os.path.join(plot_dir, os.path.basename(predfile).replace('npy', 'png')))
```

Seems like the model mistakes these green markers for maize plants. 

```{python}
cm, df, f1 = pixel_conf_mat(ds_path, target_dir, train_data_dir, predfile, class_map, result_dir=plot_dir)
```

```{python}
train_classes
```

```{python}
pred_df = pd.read_csv(predfile.replace('npy', 'csv'))

def plot_nlargest_preds(pred_df, n, cls_idx):
    
    side_len = int(n ** (1/2))

    n_largest = pred_df[(pred_df.prediction == cls_idx)].nlargest(n, 'confidence')
  
    figure, axs = plt.subplots(n, 4, figsize=(10, side_len * 10))
    for i, (idx, row) in enumerate(n_largest.iterrows()):
        bb = (row.x_min, row.x_max, row.y_min, row.y_max)
        img = to_pil_image(ds.get_bb_data(bb, normalize=False))
        prob_img = prob_mask[cls_idx, row.x_min:row.x_max, row.y_min:row.y_max]
        other_cls_idx = list(set(range(prob_mask.shape[0])) ^ {cls_idx})
        axs[i, 0].imshow(img)
        axs[i, 1].imshow(prob_mask[cls_idx, row.x_min:row.x_max, row.y_min:row.y_max])
        axs[i, 2].imshow(prob_mask[other_cls_idx[0], row.x_min:row.x_max, row.y_min:row.y_max])
        axs[i, 3].imshow(prob_mask[other_cls_idx[1], row.x_min:row.x_max, row.y_min:row.y_max])
        axs[i, 0].set_title(f"Conf: {np.around(row.confidence, 4)}")
    plt.show()
    
plot_nlargest_preds(pred_df, 5, 2)
```

<!-- #region tags=[] -->
##### Pre-trained on ImageNet
<!-- #endregion -->

version_5

```{python}
predfile = os.path.join(pred_dir, 'version_5/23-02-17_11-49_probability_map.npy')
prob_mask = np.load(predfile)
prob_mask /= prob_mask.max()
```

```{python}
figure, axs = plt.subplots(1, 3, figsize=(15, 15))
for i in range(3):
    label = train_classes[i]
    #heat_map = sns.heatmap(pd.DataFrame(data=prob_mask[i]), annot=True, cmap='Spectral', fmt='g').get_figure()
    axs[i].imshow(prob_mask[i])
    axs[i].set_title(label)
plt.savefig(os.path.join(plot_dir, os.path.basename(predfile).replace('npy', 'png')))
```

Seems like the model mistakes these green markers for maize plants. 

```{python}
cm, df, f1 = pixel_conf_mat(ds_path, target_dir, train_data_dir, predfile, class_map, result_dir=plot_dir)
```

<!-- #region tags=[] -->
#### Wide Resnet50 2
<!-- #endregion -->

version_2

```{python}
predfile = os.path.join(pred_dir, 'version_2/23-02-17_11-15_probability_map.npy')
prob_mask = np.load(predfile)
prob_mask /= prob_mask.max()
```

```{python}
figure, axs = plt.subplots(1, 3, figsize=(15, 15))
for i in range(3):
    label = train_classes[i]
    #heat_map = sns.heatmap(pd.DataFrame(data=prob_mask[i]), annot=True, cmap='Spectral', fmt='g').get_figure()
    axs[i].imshow(prob_mask[i])
    axs[i].set_title(label)
plt.savefig(os.path.join(plot_dir, os.path.basename(predfile).replace('npy', 'png')))
```

Everything is weed!

```{python}
cm, df, f1 = pixel_conf_mat(ds_path, target_dir, train_data_dir, predfile, class_map, result_dir=plot_dir)
```

version_8

```{python}
predfile = os.path.join(pred_dir, 'version_8/23-02-17_12-38_probability_map.npy')
prob_mask = np.load(predfile)
prob_mask /= prob_mask.max()
```

```{python}
figure, axs = plt.subplots(1, 3, figsize=(15, 15))
for i in range(3):
    label = train_classes[i]
    #heat_map = sns.heatmap(pd.DataFrame(data=prob_mask[i]), annot=True, cmap='Spectral', fmt='g').get_figure()
    axs[i].imshow(prob_mask[i])
    axs[i].set_title(label)
plt.savefig(os.path.join(plot_dir, os.path.basename(predfile).replace('npy', 'png')))
```

WTF

```{python}
cm, df, f1 = pixel_conf_mat(ds_path, target_dir, train_data_dir, predfile, class_map, result_dir=plot_dir)
```

#### ResNet18


version_3

```{python}
#model = InatClassifier.load_from_checkpoint(resnet18_path)
#_ = model.eval()
```

```{python}
predfile = os.path.join(pred_dir, 'version_3/23-02-17_11-37_probability_map.npy')
prob_mask = np.load(predfile)
prob_mask /= prob_mask.max()
```

```{python}
figure, axs = plt.subplots(1, 3, figsize=(15, 15))
for i in range(3):
    label = train_classes[i]
    #heat_map = sns.heatmap(pd.DataFrame(data=prob_mask[i]), annot=True, cmap='Spectral', fmt='g').get_figure()
    axs[i].imshow(prob_mask[i])
    axs[i].set_title(label)
plt.savefig(os.path.join(plot_dir, os.path.basename(predfile).replace('npy', 'png')))
```

Seems like the model mistakes these green markers for maize plants. 

```{python}
cm, df, f1 = pixel_conf_mat(ds_path, target_dir, train_data_dir, predfile, class_map, result_dir=plot_dir)
```

<!-- #region jp-MarkdownHeadingCollapsed=true tags=[] -->
##### Pre-trained
<!-- #endregion -->

version_6

```{python}
predfile = os.path.join(pred_dir, 'version_6/23-02-17_12-05_probability_map.npy')
prob_mask = np.load(predfile)
prob_mask /= prob_mask.max()
```

```{python}
figure, axs = plt.subplots(1, 3, figsize=(15, 15))
for i in range(3):
    label = train_classes[i]
    #heat_map = sns.heatmap(pd.DataFrame(data=prob_mask[i]), annot=True, cmap='Spectral', fmt='g').get_figure()
    axs[i].imshow(prob_mask[i])
    axs[i].set_title(label)
plt.savefig(os.path.join(plot_dir, os.path.basename(predfile).replace('npy', 'png')))
```

Seems like the model mistakes these green markers for maize plants. 

```{python}
cm, df, f1 = pixel_conf_mat(ds_path, target_dir, train_data_dir, predfile, class_map, result_dir=plot_dir)
```

Slight improvement with ImageNet weights

<!-- #region tags=[] -->
#### ResNest50
<!-- #endregion -->

version_4

```{python}
predfile = os.path.join(pred_dir, 'version_4/23-02-17_16-55_probability_map.npy')
prob_mask = np.load(predfile)
prob_mask /= prob_mask.max()
```

```{python}
figure, axs = plt.subplots(1, 3, figsize=(15, 15))
for i in range(3):
    label = train_classes[i]
    #heat_map = sns.heatmap(pd.DataFrame(data=prob_mask[i]), annot=True, cmap='Spectral', fmt='g').get_figure()
    axs[i].imshow(prob_mask[i])
    axs[i].set_title(label)
plt.savefig(os.path.join(plot_dir, os.path.basename(predfile).replace('npy', 'png')))
```

Predictions are more clustered per class, but the confusion with weed is worse.

```{python}
cm, df, f1 = pixel_conf_mat(ds_path, target_dir, train_data_dir, predfile, class_map, result_dir=plot_dir)
```

<!-- #region jp-MarkdownHeadingCollapsed=true tags=[] -->
##### Pre-trained on ImageNet
<!-- #endregion -->

version_7

```{python}
predfile = os.path.join(pred_dir, 'version_7/23-02-17_12-17_probability_map.npy')
prob_mask = np.load(predfile)
prob_mask /= prob_mask.max()
```

```{python}
figure, axs = plt.subplots(1, 3, figsize=(15, 15))
for i in range(3):
    label = train_classes[i]
    #heat_map = sns.heatmap(pd.DataFrame(data=prob_mask[i]), annot=True, cmap='Spectral', fmt='g').get_figure()
    axs[i].imshow(prob_mask[i])
    axs[i].set_title(label)
plt.savefig(os.path.join(plot_dir, os.path.basename(predfile).replace('npy', 'png')))
```

Predictions are more clustered per class, but the confusion with weed is worse.

```{python}
cm, df, f1 = pixel_conf_mat(ds_path, target_dir, train_data_dir, predfile, class_map, result_dir=plot_dir)
```

Plot looks good, but the confusion matrix is total chaos. Apparently even soil can't be detected properly anymore. 

<!-- #region jp-MarkdownHeadingCollapsed=true tags=[] jp-MarkdownHeadingCollapsed=true jp-MarkdownHeadingCollapsed=true tags=[] -->
### 13.06.22
<!-- #endregion -->

```{python}
pred_dir = '/home/ndettmer/experiments/ma/classification/maize_ternary/predictions/220613_maize_rgb_test_area/'
ds_path = os.path.join(test_data_dir, '220613_maize_rgb_test_area.tif')
target_dir = os.path.join(test_data_dir, '1306_maize')
ds = GTiffDataset(ds_path, stride=4, normalize=True, shape_dir=target_dir)
```

#### ResNet50


version_0

```{python}
predfile = os.path.join(pred_dir, 'version_0/23-02-17_12-59_probability_map.npy')
prob_mask = np.load(predfile)
prob_mask /= prob_mask.max()
```

```{python}
figure, axs = plt.subplots(1, 3, figsize=(15, 15))
for i in range(3):
    label = train_classes[i]
    #heat_map = sns.heatmap(pd.DataFrame(data=prob_mask[i]), annot=True, cmap='Spectral', fmt='g').get_figure()
    axs[i].imshow(prob_mask[i])
    axs[i].set_title(label)
plt.savefig(os.path.join(plot_dir, os.path.basename(predfile).replace('npy', 'png')))
```

```{python}
cm, df, f1 = pixel_conf_mat(ds_path, target_dir, train_data_dir, predfile, class_map, result_dir=plot_dir)
```

##### Pre-trained on ImageNet


version_5

```{python}
predfile = os.path.join(pred_dir, 'version_5/23-02-17_13-53_probability_map.npy')
prob_mask = np.load(predfile)
prob_mask /= prob_mask.max()
```

```{python}
figure, axs = plt.subplots(1, 3, figsize=(15, 15))
for i in range(3):
    label = train_classes[i]
    #heat_map = sns.heatmap(pd.DataFrame(data=prob_mask[i]), annot=True, cmap='Spectral', fmt='g').get_figure()
    axs[i].imshow(prob_mask[i])
    axs[i].set_title(label)
plt.savefig(os.path.join(plot_dir, os.path.basename(predfile).replace('npy', 'png')))
```

```{python}
cm, df, f1 = pixel_conf_mat(ds_path, target_dir, train_data_dir, predfile, class_map, result_dir=plot_dir)
```

##### Larger image size


version_10
- image size 256

```{python}
predfile = os.path.join(pred_dir, 'version_10/23-03-16_10-28_probability_map.npy')
prob_mask = np.load(predfile)
prob_mask /= prob_mask.max()
```

```{python}
figure, axs = plt.subplots(1, 3, figsize=(15, 15))
for i in range(3):
    label = train_classes[i]
    #heat_map = sns.heatmap(pd.DataFrame(data=prob_mask[i]), annot=True, cmap='Spectral', fmt='g').get_figure()
    axs[i].imshow(prob_mask[i])
    axs[i].set_title(label)
plt.savefig(os.path.join(plot_dir, os.path.basename(predfile).replace('npy', 'png')))
```

```{python}
cm, df, f1 = pixel_conf_mat(ds_path, target_dir, train_data_dir, predfile, class_map, result_dir=plot_dir)
```

<!-- #region tags=[] -->
#### Wide Resnet50 2
<!-- #endregion -->

version_2

```{python}
predfile = os.path.join(pred_dir, 'version_2/23-02-17_13-17_probability_map.npy')
prob_mask = np.load(predfile)
prob_mask /= prob_mask.max()
```

```{python}
figure, axs = plt.subplots(1, 3, figsize=(15, 15))
for i in range(3):
    label = train_classes[i]
    #heat_map = sns.heatmap(pd.DataFrame(data=prob_mask[i]), annot=True, cmap='Spectral', fmt='g').get_figure()
    axs[i].imshow(prob_mask[i])
    axs[i].set_title(label)
plt.savefig(os.path.join(plot_dir, os.path.basename(predfile).replace('npy', 'png')))
```

That's not too bad! Destinction between plant and soil seems to wokr quite well. Maize and weed on the other hand can hardly be distinguished. 

```{python}
cm, df, f1 = pixel_conf_mat(ds_path, target_dir, train_data_dir, predfile, class_map, result_dir=plot_dir)
```

#### ResNet18


version_3

```{python}
predfile = os.path.join(pred_dir, 'version_3/23-02-17_13-40_probability_map.npy')
prob_mask = np.load(predfile)
prob_mask /= prob_mask.max()
```

```{python}
figure, axs = plt.subplots(1, 3, figsize=(15, 15))
for i in range(3):
    label = train_classes[i]
    #heat_map = sns.heatmap(pd.DataFrame(data=prob_mask[i]), annot=True, cmap='Spectral', fmt='g').get_figure()
    axs[i].imshow(prob_mask[i])
    axs[i].set_title(label)
plt.savefig(os.path.join(plot_dir, os.path.basename(predfile).replace('npy', 'png')))
```
```{python}
cm, df, f1 = pixel_conf_mat(ds_path, target_dir, train_data_dir, predfile, class_map, result_dir=plot_dir)
```

##### Pre-trained on ImageNet


version_6

```{python}
predfile = os.path.join(pred_dir, 'version_6/23-02-17_14-12_probability_map.npy')
prob_mask = np.load(predfile)
prob_mask /= prob_mask.max()
```

```{python}
figure, axs = plt.subplots(1, 3, figsize=(15, 15))
for i in range(3):
    label = train_classes[i]
    #heat_map = sns.heatmap(pd.DataFrame(data=prob_mask[i]), annot=True, cmap='Spectral', fmt='g').get_figure()
    axs[i].imshow(prob_mask[i])
    axs[i].set_title(label)
plt.savefig(os.path.join(plot_dir, os.path.basename(predfile).replace('npy', 'png')))
```

Respectively that looks great! A lot of maize predicitons between all the weed predicitons. Most we had so far!

```{python}
cm, df, f1 = pixel_conf_mat(ds_path, target_dir, train_data_dir, predfile, class_map, result_dir=plot_dir)
```

#### ResNest50


version_4

```{python}
predfile = os.path.join(pred_dir, 'version_4/_probability_map.npy')
prob_mask = np.load(predfile)
prob_mask /= prob_mask.max()
```

```{python}
figure, axs = plt.subplots(1, 3, figsize=(15, 15))
for i in range(3):
    label = train_classes[i]
    #heat_map = sns.heatmap(pd.DataFrame(data=prob_mask[i]), annot=True, cmap='Spectral', fmt='g').get_figure()
    axs[i].imshow(prob_mask[i])
    axs[i].set_title(label)
plt.savefig(os.path.join(plot_dir, os.path.basename(predfile).replace('npy', 'png')))
```
```{python}
cm, df, f1 = pixel_conf_mat(ds_path, target_dir, train_data_dir, predfile, class_map, result_dir=plot_dir)
```

##### Pre-trained on ImageNet


version_7

```{python}
predfile = os.path.join(pred_dir, 'version_7/23-02-17_14-25_probability_map.npy')
prob_mask = np.load(predfile)
prob_mask /= prob_mask.max()
```

```{python}
figure, axs = plt.subplots(1, 3, figsize=(15, 15))
for i in range(3):
    label = train_classes[i]
    #heat_map = sns.heatmap(pd.DataFrame(data=prob_mask[i]), annot=True, cmap='Spectral', fmt='g').get_figure()
    axs[i].imshow(prob_mask[i])
    axs[i].set_title(label)
plt.savefig(os.path.join(plot_dir, os.path.basename(predfile).replace('npy', 'png')))
```
```{python}
cm, df, f1 = pixel_conf_mat(ds_path, target_dir, train_data_dir, predfile, class_map, result_dir=plot_dir)
```

##### Stride 16, Pred size 16

```{python}
predfile = os.path.join(pred_dir, 'version_7/23-03-16_11-40_probability_map.npy')
prob_mask = np.load(predfile)
prob_mask /= prob_mask.max()
```

```{python}
figure, axs = plt.subplots(1, 3, figsize=(15, 15))
for i in range(3):
    label = train_classes[i]
    #heat_map = sns.heatmap(pd.DataFrame(data=prob_mask[i]), annot=True, cmap='Spectral', fmt='g').get_figure()
    axs[i].imshow(prob_mask[i])
    axs[i].set_title(label)
plt.savefig(os.path.join(plot_dir, os.path.basename(predfile).replace('npy', 'png')))
```
```{python}
cm, df, f1 = pixel_conf_mat(ds_path, target_dir, train_data_dir, predfile, class_map, result_dir=plot_dir)
```

##### Stride 32, Pred size 32

```{python}
predfile = os.path.join(pred_dir, 'version_7/23-03-16_11-47_probability_map.npy')
prob_mask = np.load(predfile)
prob_mask /= prob_mask.max()
```

```{python}
figure, axs = plt.subplots(1, 3, figsize=(15, 15))
for i in range(3):
    label = train_classes[i]
    #heat_map = sns.heatmap(pd.DataFrame(data=prob_mask[i]), annot=True, cmap='Spectral', fmt='g').get_figure()
    axs[i].imshow(prob_mask[i])
    axs[i].set_title(label)
plt.savefig(os.path.join(plot_dir, os.path.basename(predfile).replace('npy', 'png')))
```
```{python}
cm, df, f1 = pixel_conf_mat(ds_path, target_dir, train_data_dir, predfile, class_map, result_dir=plot_dir)
```

<!-- #region tags=[] -->
## Maize ternary, manually Pre-selected training data
<!-- #endregion -->

<!-- #region tags=[] jp-MarkdownHeadingCollapsed=true -->
### 18.05.22
<!-- #endregion -->

```{python}
plot_dir = '/home/ndettmer/experiments/ma/classification/maize_ternary_manual_preselect/plots'
pred_dir = '/home/ndettmer/experiments/ma/classification/maize_ternary_manual_preselect/predictions/220518_maize_rgb_test_area/'
train_data_dir = '/home/ndettmer/ssd_data/inat_subsets/maize_ternary_manual_preselect/'
ds_path = os.path.join(test_data_dir, '220518_maize_rgb_test_area.tif')
target_dir = os.path.join(test_data_dir, '1805_maize')
ds = GTiffDataset(ds_path, stride=4, normalize=True, shape_dir=target_dir)
```

<!-- #region tags=[] jp-MarkdownHeadingCollapsed=true jp-MarkdownHeadingCollapsed=true tags=[] -->
#### version_0
- image size 128
- pred size 16
- stride 16
<!-- #endregion -->

```{python}
predfile = os.path.join(pred_dir, 'version_0/23-03-16_16-20_probability_map.npy')
prob_mask = np.load(predfile)
prob_mask /= prob_mask.max()
```

```{python}
figure, axs = plt.subplots(1, 3, figsize=(15, 15))
for i in range(3):
    label = train_classes[i]
    #heat_map = sns.heatmap(pd.DataFrame(data=prob_mask[i]), annot=True, cmap='Spectral', fmt='g').get_figure()
    axs[i].imshow(prob_mask[i])
    axs[i].set_title(label)
plt.savefig(os.path.join(plot_dir, os.path.basename(predfile).replace('npy', 'png')))
```

```{python}
cm, df, f1 = pixel_conf_mat(ds_path, target_dir, train_data_dir, predfile, class_map, result_dir=plot_dir)
```

<!-- #region tags=[] jp-MarkdownHeadingCollapsed=true jp-MarkdownHeadingCollapsed=true tags=[] -->
#### version_1
- image size 256
- pred size 16
- stride 16
<!-- #endregion -->

```{python}
predfile = os.path.join(pred_dir, 'version_1/23-03-16_16-29_probability_map.npy')
prob_mask = np.load(predfile)
prob_mask /= prob_mask.max()
```

```{python}
figure, axs = plt.subplots(1, 3, figsize=(15, 15))
for i in range(3):
    label = train_classes[i]
    #heat_map = sns.heatmap(pd.DataFrame(data=prob_mask[i]), annot=True, cmap='Spectral', fmt='g').get_figure()
    axs[i].imshow(prob_mask[i])
    axs[i].set_title(label)
plt.savefig(os.path.join(plot_dir, os.path.basename(predfile).replace('npy', 'png')))
```

```{python}
cm, df, f1 = pixel_conf_mat(ds_path, target_dir, train_data_dir, predfile, class_map, result_dir=plot_dir)
```

<!-- #region tags=[] jp-MarkdownHeadingCollapsed=true jp-MarkdownHeadingCollapsed=true tags=[] -->
#### version_2
- image size 128
- pred size 16
- stride 16
<!-- #endregion -->

```{python}
predfile = os.path.join(pred_dir, 'version_2/23-03-16_16-34_probability_map.npy')
prob_mask = np.load(predfile)
prob_mask /= prob_mask.max()
```

```{python}
figure, axs = plt.subplots(1, 3, figsize=(15, 15))
for i in range(3):
    label = train_classes[i]
    #heat_map = sns.heatmap(pd.DataFrame(data=prob_mask[i]), annot=True, cmap='Spectral', fmt='g').get_figure()
    axs[i].imshow(prob_mask[i])
    axs[i].set_title(label)
plt.savefig(os.path.join(plot_dir, os.path.basename(predfile).replace('npy', 'png')))
```

```{python}
cm, df, f1 = pixel_conf_mat(ds_path, target_dir, train_data_dir, predfile, class_map, result_dir=plot_dir)
```

<!-- #region tags=[] jp-MarkdownHeadingCollapsed=true -->
#### version_3
- image size 128
- pred size 16
- stride 16
<!-- #endregion -->

```{python}
predfile = os.path.join(pred_dir, 'version_3/23-03-16_16-13_probability_map.npy')
prob_mask = np.load(predfile)
prob_mask /= prob_mask.max()
```

```{python}
figure, axs = plt.subplots(1, 3, figsize=(15, 15))
for i in range(3):
    label = train_classes[i]
    #heat_map = sns.heatmap(pd.DataFrame(data=prob_mask[i]), annot=True, cmap='Spectral', fmt='g').get_figure()
    axs[i].imshow(prob_mask[i])
    axs[i].set_title(label)
plt.savefig(os.path.join(plot_dir, os.path.basename(predfile).replace('npy', 'png')))
```

```{python}
cm, df, f1 = pixel_conf_mat(ds_path, target_dir, train_data_dir, predfile, class_map, result_dir=plot_dir)
```

```{python}
pred_df = pd.read_csv(predfile.replace('npy', 'csv'))

def plot_nlargest_preds(pred_df, n, cls_idx):
    
    side_len = int(n ** (1/2))

    n_largest = pred_df[(pred_df.prediction == cls_idx)].nlargest(n, 'confidence')
  
    figure, axs = plt.subplots(n, 4, figsize=(10, side_len * 10))
    for i, (idx, row) in enumerate(n_largest.iterrows()):
        bb = (row.x_min, row.x_max, row.y_min, row.y_max)
        img = to_pil_image(ds.get_bb_data(bb, normalize=False))
        prob_img = prob_mask[cls_idx, row.x_min:row.x_max, row.y_min:row.y_max]
        other_cls_idx = list(set(range(prob_mask.shape[0])) ^ {cls_idx})
        axs[i, 0].imshow(img)
        axs[i, 1].imshow(prob_mask[cls_idx, row.x_min:row.x_max, row.y_min:row.y_max])
        axs[i, 2].imshow(prob_mask[other_cls_idx[0], row.x_min:row.x_max, row.y_min:row.y_max])
        axs[i, 3].imshow(prob_mask[other_cls_idx[1], row.x_min:row.x_max, row.y_min:row.y_max])
        axs[i, 0].set_title(f"Conf: {np.around(row.confidence, 4)}")
        axs[i, 1].set_title(train_classes[cls_idx])
        axs[i, 2].set_title(train_classes[other_cls_idx[0]])
        axs[i, 3].set_title(train_classes[other_cls_idx[1]])
    plt.show()
    
plot_nlargest_preds(pred_df, 5, 2)
```

<!-- #region tags=[] -->
#### version_4
- image size 128
- pred size 16
- stride 16
<!-- #endregion -->

```{python}
predfile = os.path.join(pred_dir, 'version_4/23-03-17_09-23_probability_map.npy')
prob_mask = np.load(predfile)
prob_mask /= prob_mask.max()
```

```{python}
figure, axs = plt.subplots(1, 3, figsize=(15, 15))
for i in range(3):
    label = train_classes[i]
    #heat_map = sns.heatmap(pd.DataFrame(data=prob_mask[i]), annot=True, cmap='Spectral', fmt='g').get_figure()
    axs[i].imshow(prob_mask[i])
    axs[i].set_title(label)
plt.savefig(os.path.join(plot_dir, os.path.basename(predfile).replace('npy', 'png')))
```

```{python}
cm, df, f1 = pixel_conf_mat(ds_path, target_dir, train_data_dir, predfile, class_map, result_dir=plot_dir)
```

```{python}
pred_df = pd.read_csv(predfile.replace('npy', 'csv'))

def plot_nlargest_preds(pred_df, n, cls_idx):
    
    side_len = int(n ** (1/2))

    n_largest = pred_df[(pred_df.prediction == cls_idx)].nlargest(n, 'confidence')
  
    figure, axs = plt.subplots(n, 4, figsize=(10, side_len * 10))
    for i, (idx, row) in enumerate(n_largest.iterrows()):
        bb = (row.x_min, row.x_max, row.y_min, row.y_max)
        img = to_pil_image(ds.get_bb_data(bb, normalize=False))
        prob_img = prob_mask[cls_idx, row.x_min:row.x_max, row.y_min:row.y_max]
        other_cls_idx = list(set(range(prob_mask.shape[0])) ^ {cls_idx})
        axs[i, 0].imshow(img)
        axs[i, 1].imshow(prob_mask[cls_idx, row.x_min:row.x_max, row.y_min:row.y_max])
        axs[i, 2].imshow(prob_mask[other_cls_idx[0], row.x_min:row.x_max, row.y_min:row.y_max])
        axs[i, 3].imshow(prob_mask[other_cls_idx[1], row.x_min:row.x_max, row.y_min:row.y_max])
        axs[i, 0].set_title(f"Conf: {np.around(row.confidence, 4)}")
        axs[i, 1].set_title(train_classes[cls_idx])
        axs[i, 2].set_title(train_classes[other_cls_idx[0]])
        axs[i, 3].set_title(train_classes[other_cls_idx[1]])
    plt.show()
    
plot_nlargest_preds(pred_df, 5, 2)
```

<!-- #region tags=[] jp-MarkdownHeadingCollapsed=true -->
#### version_5
- image size 128
- pred size 16
- stride 16
<!-- #endregion -->

```{python}
predfile = os.path.join(pred_dir, 'version_5/23-03-17_09-24_probability_map.npy')
prob_mask = np.load(predfile)
prob_mask /= prob_mask.max()
```

```{python}
figure, axs = plt.subplots(1, 3, figsize=(15, 15))
for i in range(3):
    label = train_classes[i]
    #heat_map = sns.heatmap(pd.DataFrame(data=prob_mask[i]), annot=True, cmap='Spectral', fmt='g').get_figure()
    axs[i].imshow(prob_mask[i])
    axs[i].set_title(label)
plt.savefig(os.path.join(plot_dir, os.path.basename(predfile).replace('npy', 'png')))
```

```{python}
cm, df, f1 = pixel_conf_mat(ds_path, target_dir, train_data_dir, predfile, class_map, result_dir=plot_dir)
```

<!-- #region tags=[] jp-MarkdownHeadingCollapsed=true -->
#### version_6
- image size 128
- pred size 16
- stride 16
- MogaNet
<!-- #endregion -->

```{python}
predfile = os.path.join(pred_dir, 'version_6/23-03-17_19-49_probability_map.npy')
prob_mask = np.load(predfile)
prob_mask /= prob_mask.max()
```

```{python}
figure, axs = plt.subplots(1, 3, figsize=(15, 15))
for i in range(3):
    label = train_classes[i]
    #heat_map = sns.heatmap(pd.DataFrame(data=prob_mask[i]), annot=True, cmap='Spectral', fmt='g').get_figure()
    axs[i].imshow(prob_mask[i])
    axs[i].set_title(label)
plt.savefig(os.path.join(plot_dir, os.path.basename(predfile).replace('npy', 'png')))
```

```{python}
cm, df, f1 = pixel_conf_mat(ds_path, target_dir, train_data_dir, predfile, class_map, result_dir=plot_dir)
```

<!-- #region tags=[] jp-MarkdownHeadingCollapsed=true tags=[] -->
### 13.06.22
<!-- #endregion -->

```{python}
plot_dir = '/home/ndettmer/experiments/ma/classification/maize_ternary_manual_preselect/plots'
pred_dir = '/home/ndettmer/experiments/ma/classification/maize_ternary_manual_preselect/predictions/220613_maize_rgb_test_area/'
train_data_dir = '/home/ndettmer/ssd_data/inat_subsets/maize_ternary_manual_preselect/'
ds_path = os.path.join(test_data_dir, '220518_maize_rgb_test_area.tif')
target_dir = os.path.join(test_data_dir, '1306_maize')
ds = GTiffDataset(ds_path, stride=4, normalize=True, shape_dir=target_dir)
```

<!-- #region tags=[] jp-MarkdownHeadingCollapsed=true jp-MarkdownHeadingCollapsed=true tags=[] jp-MarkdownHeadingCollapsed=true -->
#### version_0
- image size 128
- pred size 16
- stride 16
<!-- #endregion -->

```{python}
predfile = os.path.join(pred_dir, 'version_0/23-03-13_15-58_probability_map.npy')
prob_mask = np.load(predfile)
prob_mask /= prob_mask.max()
```

```{python}
figure, axs = plt.subplots(1, 3, figsize=(15, 15))
for i in range(3):
    label = train_classes[i]
    #heat_map = sns.heatmap(pd.DataFrame(data=prob_mask[i]), annot=True, cmap='Spectral', fmt='g').get_figure()
    axs[i].imshow(prob_mask[i])
    axs[i].set_title(label)
plt.savefig(os.path.join(plot_dir, os.path.basename(predfile).replace('npy', 'png')))
```

```{python}
cm, df, f1 = pixel_conf_mat(ds_path, target_dir, train_data_dir, predfile, class_map, result_dir=plot_dir)
```

```{python}
pred_df = pd.read_csv(predfile.replace('npy', 'csv'))

def plot_nlargest_preds(pred_df, n, cls_idx):
    
    side_len = int(n ** (1/2))

    n_largest = pred_df[(pred_df.prediction == cls_idx)].nlargest(n, 'confidence')
  
    figure, axs = plt.subplots(n, 4, figsize=(10, side_len * 10))
    for i, (idx, row) in enumerate(n_largest.iterrows()):
        bb = (row.x_min, row.x_max, row.y_min, row.y_max)
        img = to_pil_image(ds.get_bb_data(bb, normalize=False))
        prob_img = prob_mask[cls_idx, row.x_min:row.x_max, row.y_min:row.y_max]
        other_cls_idx = list(set(range(prob_mask.shape[0])) ^ {cls_idx})
        axs[i, 0].imshow(img)
        axs[i, 1].imshow(prob_mask[cls_idx, row.x_min:row.x_max, row.y_min:row.y_max])
        axs[i, 2].imshow(prob_mask[other_cls_idx[0], row.x_min:row.x_max, row.y_min:row.y_max])
        axs[i, 3].imshow(prob_mask[other_cls_idx[1], row.x_min:row.x_max, row.y_min:row.y_max])
        axs[i, 0].set_title(f"Conf: {np.around(row.confidence, 4)}")
        axs[i, 1].set_title(train_classes[cls_idx])
        axs[i, 2].set_title(train_classes[other_cls_idx[0]])
        axs[i, 3].set_title(train_classes[other_cls_idx[1]])
    plt.show()
    
plot_nlargest_preds(pred_df, 5, 2)
```

<!-- #region tags=[] jp-MarkdownHeadingCollapsed=true jp-MarkdownHeadingCollapsed=true tags=[] jp-MarkdownHeadingCollapsed=true -->
#### version_1
- image size 256
- pred size 16
- stride 16
<!-- #endregion -->

```{python}
predfile = os.path.join(pred_dir, 'version_1/23-03-13_21-25_probability_map.npy')
prob_mask = np.load(predfile)
prob_mask /= prob_mask.max()
```

```{python}
figure, axs = plt.subplots(1, 3, figsize=(15, 15))
for i in range(3):
    label = train_classes[i]
    #heat_map = sns.heatmap(pd.DataFrame(data=prob_mask[i]), annot=True, cmap='Spectral', fmt='g').get_figure()
    axs[i].imshow(prob_mask[i])
    axs[i].set_title(label)
plt.savefig(os.path.join(plot_dir, os.path.basename(predfile).replace('npy', 'png')))
```

```{python}
cm, df, f1 = pixel_conf_mat(ds_path, target_dir, train_data_dir, predfile, class_map, result_dir=plot_dir)
```

```{python}
pred_df = pd.read_csv(predfile.replace('npy', 'csv'))

def plot_nlargest_preds(pred_df, n, cls_idx):
    
    side_len = int(n ** (1/2))

    n_largest = pred_df[(pred_df.prediction == cls_idx)].nlargest(n, 'confidence')
  
    figure, axs = plt.subplots(n, 4, figsize=(10, side_len * 10))
    for i, (idx, row) in enumerate(n_largest.iterrows()):
        bb = (row.x_min, row.x_max, row.y_min, row.y_max)
        img = to_pil_image(ds.get_bb_data(bb, normalize=False))
        prob_img = prob_mask[cls_idx, row.x_min:row.x_max, row.y_min:row.y_max]
        other_cls_idx = list(set(range(prob_mask.shape[0])) ^ {cls_idx})
        axs[i, 0].imshow(img)
        axs[i, 1].imshow(prob_mask[cls_idx, row.x_min:row.x_max, row.y_min:row.y_max])
        axs[i, 2].imshow(prob_mask[other_cls_idx[0], row.x_min:row.x_max, row.y_min:row.y_max])
        axs[i, 3].imshow(prob_mask[other_cls_idx[1], row.x_min:row.x_max, row.y_min:row.y_max])
        axs[i, 0].set_title(f"Conf: {np.around(row.confidence, 4)}")
        axs[i, 1].set_title(train_classes[cls_idx])
        axs[i, 2].set_title(train_classes[other_cls_idx[0]])
        axs[i, 3].set_title(train_classes[other_cls_idx[1]])
    plt.show()
    
plot_nlargest_preds(pred_df, 5, 2)
```

<!-- #region jp-MarkdownHeadingCollapsed=true tags=[] -->
#### version_2
- image_size 128
- stride 16
- pred size 16
<!-- #endregion -->

```{python}
predfile = os.path.join(pred_dir, 'version_2/23-03-16_14-04_probability_map.npy')
prob_mask = np.load(predfile)
prob_mask /= prob_mask.max()
```

```{python}
figure, axs = plt.subplots(1, 3, figsize=(15, 15))
for i in range(3):
    label = train_classes[i]
    #heat_map = sns.heatmap(pd.DataFrame(data=prob_mask[i]), annot=True, cmap='Spectral', fmt='g').get_figure()
    axs[i].imshow(prob_mask[i])
    axs[i].set_title(label)
plt.savefig(os.path.join(plot_dir, os.path.basename(predfile).replace('npy', 'png')))
```

```{python}
cm, df, f1 = pixel_conf_mat(ds_path, target_dir, train_data_dir, predfile, class_map, result_dir=plot_dir)
```

<!-- #region jp-MarkdownHeadingCollapsed=true tags=[] jp-MarkdownHeadingCollapsed=true -->
#### version_3
- image_size 128
- stride 16
- pred size 16
<!-- #endregion -->

```{python}
predfile = os.path.join(pred_dir, 'version_3/23-03-16_16-02_probability_map.npy')
prob_mask = np.load(predfile)
prob_mask /= prob_mask.max()
```

```{python}
figure, axs = plt.subplots(1, 3, figsize=(15, 15))
for i in range(3):
    label = train_classes[i]
    #heat_map = sns.heatmap(pd.DataFrame(data=prob_mask[i]), annot=True, cmap='Spectral', fmt='g').get_figure()
    axs[i].imshow(prob_mask[i])
    axs[i].set_title(label)
plt.savefig(os.path.join(plot_dir, os.path.basename(predfile).replace('npy', 'png')))
```

```{python}
cm, df, f1 = pixel_conf_mat(ds_path, target_dir, train_data_dir, predfile, class_map, result_dir=plot_dir)
```

<!-- #region jp-MarkdownHeadingCollapsed=true tags=[] jp-MarkdownHeadingCollapsed=true -->
#### version_4
- image_size 128
- stride 16
- pred size 16
<!-- #endregion -->

```{python}
predfile = os.path.join(pred_dir, 'version_4/23-03-17_09-20_probability_map.npy')
prob_mask = np.load(predfile)
prob_mask /= prob_mask.max()
```

```{python}
figure, axs = plt.subplots(1, 3, figsize=(15, 15))
for i in range(3):
    label = train_classes[i]
    #heat_map = sns.heatmap(pd.DataFrame(data=prob_mask[i]), annot=True, cmap='Spectral', fmt='g').get_figure()
    axs[i].imshow(prob_mask[i])
    axs[i].set_title(label)
plt.savefig(os.path.join(plot_dir, os.path.basename(predfile).replace('npy', 'png')))
```

```{python}
cm, df, f1 = pixel_conf_mat(ds_path, target_dir, train_data_dir, predfile, class_map, result_dir=plot_dir)
```

<!-- #region jp-MarkdownHeadingCollapsed=true tags=[] jp-MarkdownHeadingCollapsed=true -->
#### version_5
- image_size 128
- stride 16
- pred size 16
<!-- #endregion -->

```{python}
predfile = os.path.join(pred_dir, 'version_5/23-03-17_09-22_probability_map.npy')
prob_mask = np.load(predfile)
prob_mask /= prob_mask.max()
```

```{python}
figure, axs = plt.subplots(1, 3, figsize=(15, 15))
for i in range(3):
    label = train_classes[i]
    #heat_map = sns.heatmap(pd.DataFrame(data=prob_mask[i]), annot=True, cmap='Spectral', fmt='g').get_figure()
    axs[i].imshow(prob_mask[i])
    axs[i].set_title(label)
plt.savefig(os.path.join(plot_dir, os.path.basename(predfile).replace('npy', 'png')))
```

```{python}
cm, df, f1 = pixel_conf_mat(ds_path, target_dir, train_data_dir, predfile, class_map, result_dir=plot_dir)
```

<!-- #region jp-MarkdownHeadingCollapsed=true tags=[] -->
#### version_6
- image_size 128
- stride 16
- pred size 16
- MogaNet
<!-- #endregion -->

```{python}
predfile = os.path.join(pred_dir, 'version_6/23-03-17_19-51_probability_map.npy')
prob_mask = np.load(predfile)
prob_mask /= prob_mask.max()
```

```{python}
figure, axs = plt.subplots(1, 3, figsize=(15, 15))
for i in range(3):
    label = train_classes[i]
    #heat_map = sns.heatmap(pd.DataFrame(data=prob_mask[i]), annot=True, cmap='Spectral', fmt='g').get_figure()
    axs[i].imshow(prob_mask[i])
    axs[i].set_title(label)
plt.savefig(os.path.join(plot_dir, os.path.basename(predfile).replace('npy', 'png')))
```

```{python}
cm, df, f1 = pixel_conf_mat(ds_path, target_dir, train_data_dir, predfile, class_map, result_dir=plot_dir)
```

<!-- #region tags=[] -->
## Maize ternary with raster data
<!-- #endregion -->

```{python}
train_classes = InatDataModule('/home/ndettmer/ssd_data/mixed_datasets/maize_ternary/inat-manual_raster/').ds.classes
```

### 18.05.22

```{python}
plot_dir = '/home/ndettmer/experiments/ma/classification/maize_ternary_mixed_training_data/plots'
pred_dir = '/home/ndettmer/experiments/ma/classification/maize_ternary_mixed_training_data/predictions/220518_maize_rgb_test_area/'
train_data_dir = '/home/ndettmer/ssd_data/mixed_datasets/maize_ternary/inat-manual_raster/'
ds_path = os.path.join(test_data_dir, '220518_maize_rgb_test_area.tif')
target_dir = os.path.join(test_data_dir, '1805_maize')
ds = GTiffDataset(ds_path, stride=4, normalize=True, shape_dir=target_dir)
```

<!-- #region tags=[] jp-MarkdownHeadingCollapsed=true -->
#### version_0
- image size 128
- pred size 16
- stride 16
<!-- #endregion -->

```{python}
predfile = os.path.join(pred_dir, 'version_0/23-04-20_17-07_probability_map.npy')
prob_mask = np.load(predfile)
prob_mask /= prob_mask.max()
```

```{python}
figure, axs = plt.subplots(1, 3, figsize=(15, 15))
for i in range(3):
    label = train_classes[i]
    #heat_map = sns.heatmap(pd.DataFrame(data=prob_mask[i]), annot=True, cmap='Spectral', fmt='g').get_figure()
    axs[i].imshow(prob_mask[i])
    axs[i].set_title(label)
plt.savefig(os.path.join(plot_dir, os.path.basename(predfile).replace('npy', 'png')))
```

```{python}
cm, df, f1 = pixel_conf_mat(ds_path, target_dir, train_data_dir, predfile, json.dumps({c: c for c in train_classes}), result_dir=plot_dir)
```

<!-- #region tags=[] jp-MarkdownHeadingCollapsed=true -->
#### version_1
- image size 128
- pred size 16
- stride 16
<!-- #endregion -->

```{python}
predfile = os.path.join(pred_dir, 'version_1/23-04-20_17-58_probability_map.npy')
prob_mask = np.load(predfile)
prob_mask /= prob_mask.max()
```

```{python}
figure, axs = plt.subplots(1, 3, figsize=(15, 15))
for i in range(3):
    label = train_classes[i]
    #heat_map = sns.heatmap(pd.DataFrame(data=prob_mask[i]), annot=True, cmap='Spectral', fmt='g').get_figure()
    axs[i].imshow(prob_mask[i])
    axs[i].set_title(label)
plt.savefig(os.path.join(plot_dir, os.path.basename(predfile).replace('npy', 'png')))
```

```{python}
cm, df, f1 = pixel_conf_mat(ds_path, target_dir, train_data_dir, predfile, json.dumps({c: c for c in train_classes}), result_dir=plot_dir)
```

<!-- #region tags=[] -->
### 13.06.22
<!-- #endregion -->

```{python}
plot_dir = '/home/ndettmer/experiments/ma/classification/maize_ternary_mixed_training_data/plots'
pred_dir = '/home/ndettmer/experiments/ma/classification/maize_ternary_mixed_training_data/predictions/220613_maize_rgb_test_area/'
train_data_dir = '/home/ndettmer/ssd_data/mixed_datasets/maize_ternary/inat-manual_raster/'
ds_path = os.path.join(test_data_dir, '220613_maize_rgb_test_area.tif')
target_dir = os.path.join(test_data_dir, '1306_maize')
ds = GTiffDataset(ds_path, stride=4, normalize=True, shape_dir=target_dir)
```

<!-- #region tags=[] jp-MarkdownHeadingCollapsed=true -->
#### version_0
- image size 128
- pred size 16
- stride 16
<!-- #endregion -->

```{python}
predfile = os.path.join(pred_dir, 'version_0/23-04-20_16-50_probability_map.npy')
prob_mask = np.load(predfile)
prob_mask /= prob_mask.max()
```

```{python}
figure, axs = plt.subplots(1, 3, figsize=(15, 15))
for i in range(3):
    label = train_classes[i]
    #heat_map = sns.heatmap(pd.DataFrame(data=prob_mask[i]), annot=True, cmap='Spectral', fmt='g').get_figure()
    axs[i].imshow(prob_mask[i])
    axs[i].set_title(label)
plt.savefig(os.path.join(plot_dir, os.path.basename(predfile).replace('npy', 'png')))
```

```{python}
cm, df, f1 = pixel_conf_mat(ds_path, target_dir, train_data_dir, predfile, json.dumps({c: c for c in train_classes}), result_dir=plot_dir)
```

<!-- #region tags=[] jp-MarkdownHeadingCollapsed=true -->
#### version_1
- image size 128
- pred size 16
- stride 16
<!-- #endregion -->

```{python}
predfile = os.path.join(pred_dir, 'version_1/23-04-20_18-00_probability_map.npy')
prob_mask = np.load(predfile)
prob_mask /= prob_mask.max()
```

```{python}
figure, axs = plt.subplots(1, 3, figsize=(15, 15))
for i in range(3):
    label = train_classes[i]
    #heat_map = sns.heatmap(pd.DataFrame(data=prob_mask[i]), annot=True, cmap='Spectral', fmt='g').get_figure()
    axs[i].imshow(prob_mask[i])
    axs[i].set_title(label)
plt.savefig(os.path.join(plot_dir, os.path.basename(predfile).replace('npy', 'png')))
```

```{python}
cm, df, f1 = pixel_conf_mat(ds_path, target_dir, train_data_dir, predfile, json.dumps({c: c for c in train_classes}), result_dir=plot_dir)
```

## Maize ternary raster data only

```{python}
train_classes = InatDataModule('/home/ndettmer/ssd_data/UOS_Data/maize_ternary_valds_mixed/').ds.classes
```

### 13.05.22

```{python}
plot_dir = '/home/ndettmer/experiments/ma/classification/maize_ternary_raster_training_data/plots'
pred_dir = '/home/ndettmer/experiments/ma/classification/maize_ternary_raster_training_data/predictions/220518_maize_rgb_test_area/'
train_data_dir = '/home/ndettmer/ssd_data/mixed_datasets/maize_ternary/inat-manual_raster/'
ds_path = os.path.join(test_data_dir, '220518_maize_rgb_test_area.tif')
target_dir = os.path.join(test_data_dir, '1805_maize')
ds = GTiffDataset(ds_path, stride=4, normalize=True, shape_dir=target_dir)
```

<!-- #region tags=[] jp-MarkdownHeadingCollapsed=true -->
#### version_0
<!-- #endregion -->

```{python}
predfile = os.path.join(pred_dir, 'version_0/23-04-24_11-04_probability_map.npy')
prob_mask = np.load(predfile)
prob_mask /= prob_mask.max()
```

```{python}
figure, axs = plt.subplots(1, 3, figsize=(15, 15))
for i in range(3):
    label = train_classes[i]
    #heat_map = sns.heatmap(pd.DataFrame(data=prob_mask[i]), annot=True, cmap='Spectral', fmt='g').get_figure()
    axs[i].imshow(prob_mask[i])
    axs[i].set_title(label)
plt.savefig(os.path.join(plot_dir, os.path.basename(predfile).replace('npy', 'png')))
```

```{python}
cm, df, f1 = pixel_conf_mat(ds_path, target_dir, train_data_dir, predfile, None, result_dir=plot_dir)
```

```{python}

```
